name: Clear Draft Releases

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  clear-draft-releases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Clear draft releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Fetching draft releases..."
        response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases)

        echo "Response: $response"

        drafts=$(echo "$response" | jq -r '.[] | select(.draft == true) | .id')

        echo "Draft releases found: $drafts"

        if [ -z "$drafts" ]; then
          echo "No draft releases found."
        else
          for id in $drafts; do
            echo "Deleting draft release with ID: $id"
            delete_response=$(curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/releases/$id)

            echo "Delete response for ID $id: $delete_response"
          done
          echo "Draft releases cleared."
        fi
