name: Delete Tags and Releases

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  delete-tags-releases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete all tags
      run: |
        tags=$(git tag -l)
        if [ -n "$tags" ]; then
          for tag in $tags; do
            git push origin :refs/tags/$tag
            git tag -d $tag
          done
        else
          echo "No tags found."
        fi

    - name: Get releases
      id: get_releases
      run: |
        releases=$(gh api repos/${{ github.repository }}/releases -q '.[].id')
        echo "releases=$releases" >> $GITHUB_ENV

    - name: Delete releases
      if: env.releases != ''
      run: |
        for release in ${{ env.releases }}; do
          gh api --method DELETE repos/${{ github.repository }}/releases/${release}
        done

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
