name: Delete Tags and Releases

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  delete-tags-releases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete all tags
      run: |
        git tag -l | xargs -n 1 git push --delete origin
        git tag -l | xargs git tag -d

    - name: Get releases
      id: releases
      run: |
        releases=$(gh api repos/${{ github.repository }}/releases -q '.[].id')
        echo "::set-output name=releases::${releases}"

    - name: Delete releases
      if: steps.releases.outputs.releases != ''
      run: |
        for release in ${{ steps.releases.outputs.releases }}
        do
          gh api --method DELETE repos/${{ github.repository }}/releases/${release}
        done

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
