name: Delete Tags and Releases

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  delete-tags-releases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Delete all tags
      run: |
        tags=$(git tag -l)
        if [ -n "$tags" ]; then
          for tag in $tags; do
            git push origin :refs/tags/$tag
            git tag -d $tag
          done
        else
          echo "No tags found."
        fi

    - name: Get releases
      id: get_releases
      run: |
        gh api repos/${{ github.repository }}/releases -q '.[].id' > releases.txt

    - name: Delete releases
      run: |
        if [ -s releases.txt ]; then
          while IFS= read -r release; do
            gh api --method DELETE repos/${{ github.repository }}/releases/${release}
          done < releases.txt
        else
          echo "No releases found."
        fi

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
